https://www.kaggle.com/datasets/arianazmoudeh/airbnbopendata

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [2]:
airbnb = pd.read_csv("Airbnb_Open_Data.csv")

In [3]:
airbnb.head()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,...,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,...,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,...,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,...,$74,30.0,270.0,7/5/2019,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,...,$41,10.0,9.0,11/19/2018,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [4]:
airbnb.tail()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,...,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,...,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,...,$167,1.0,1.0,7/6/2015,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,...,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,...,$109,2.0,5.0,10/11/2015,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,...,$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [5]:
airbnb.shape

(102599, 26)

In [6]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

### Copy data

In [7]:
df = airbnb.copy()

In [8]:
keep_cols = [
    "host_identity_verified", "neighbourhood group", "neighbourhood",
    "lat", "long", "room type", "Construction year", 
    "price", "service fee", "minimum nights", 
    "number of reviews", "review rate number", "calculated host listings count", 
    "availability 365", "cancellation_policy", "instant_bookable"
]

df = df[keep_cols]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 16 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   host_identity_verified          102310 non-null  object
 1   neighbourhood group             102570 non-null  object
 2   neighbourhood                   102583 non-null  object
 3   lat                             102591 non-null  float64
 4   long                            102591 non-null  float64
 5   room type                       102599 non-null  object
 6   Construction year               102385 non-null  float64
 7   price                           102352 non-null  object
 8   service fee                     102326 non-null  object
 9   minimum nights                  102190 non-null  float64
 10  number of reviews               102416 non-null  float64
 11  review rate number              102273 non-null  float64
 12  calculated host listings count  102280 non-null  float64
 13  availability 365                102151 non-null  float64
 14  cancellation_policy             102523 non-null  object
 15  instant_bookable                102494 non-null  object
dtypes: float64(8), object(8)
memory usage: 12.5+ MB

In [ ]:
# export to excel for manual assesment 
df.to_excel("bnb.xlsx")

## issues with dataset
- All columns contain some missing values. </br>
- The `room type` column mixes different property categories (Entire home/apt).
- `availability 365` column contains negative values and values greater than 365, which are not valid.
- `minimum nights` column contains negative values, which are not logically possible.

In [10]:
df.isnull().mean()*100

host_identity_verified            0.281679
neighbourhood group               0.028265
neighbourhood                     0.015595
lat                               0.007797
long                              0.007797
room type                         0.000000
Construction year                 0.208579
price                             0.240743
service fee                       0.266084
minimum nights                    0.398639
number of reviews                 0.178364
review rate number                0.317742
calculated host listings count    0.310919
availability 365                  0.436651
cancellation_policy               0.074075
instant_bookable                  0.102340
dtype: float64

In [13]:
df[df['availability 365'] < 0]

,host_identity_verified,neighbourhood group,neighbourhood,lat,long,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,cancellation_policy,instant_bookable
236,unconfirmed,Manhattan,East Harlem,40.79163,-73.94573,Entire home/apt,2020.0,"$1,052",$210,28.0,183.0,2.0,2.0,-6.0,flexible,False
308,verified,Manhattan,West Village,40.72966,-74.00243,Entire home/apt,2010.0,$935,$187,30.0,39.0,2.0,1.0,-9.0,strict,True
490,verified,Manhattan,Harlem,40.80224,-73.94558,Private room,2016.0,$424,$85,2.0,17.0,3.0,2.0,-9.0,moderate,True
529,verified,Manhattan,Hell's Kitchen,40.77090,-73.99181,Private room,2021.0,$619,$124,28.0,43.0,5.0,2.0,-4.0,moderate,False
561,verified,Brooklyn,Sheepshead Bay,40.58422,-73.94079,Entire home/apt,2007.0,$441,$88,4.0,128.0,2.0,2.0,-8.0,moderate,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86735,unconfirmed,Manhattan,East Village,40.72627,-73.99145,Entire home/apt,2005.0,$335,$67,3.0,27.0,5.0,1.0,-4.0,moderate,True
86764,verified,Queens,Ridgewood,40.70971,-73.89741,Entire home/apt,2009.0,$606,$121,28.0,1.0,4.0,1.0,-2.0,flexible,False
86790,unconfirmed,Manhattan,Harlem,40.81863,-73.95295,Private room,2017.0,$948,$190,2.0,0.0,4.0,3.0,-7.0,strict,False
86853,unconfirmed,Manhattan,Chelsea,40.74584,-74.00279,Entire home/apt,2004.0,$651,$130,14.0,0.0,5.0,1.0,-7.0,flexible,True
102559,verified,Brooklyn,Bedford-Stuyvesant,40.68110,-73.95275,Private room,2004.0,$441,$88,1.0,0.0,2.0,1.0,-6.0,moderate,True

In [14]:
df[df['minimum nights'] < 0]

,host_identity_verified,neighbourhood group,neighbourhood,lat,long,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,cancellation_policy,instant_bookable
176,unconfirmed,Brooklyn,Fort Greene,40.69098,-73.97113,Private room,2008.0,"$1,155",$231,-10.0,213.0,5.0,2.0,19.0,flexible,False
398,verified,Brooklyn,Kensington,40.64302,-73.97255,Private room,2015.0,$779,$156,-1.0,82.0,2.0,2.0,131.0,flexible,False
421,verified,Manhattan,Nolita,40.72094,-73.99706,Entire home/apt,2008.0,$874,$175,-10.0,68.0,5.0,1.0,13.0,flexible,False
441,verified,Manhattan,Harlem,40.80497,-73.95016,Entire home/apt,2021.0,$920,$184,-12.0,203.0,5.0,3.0,77.0,moderate,False
478,unconfirmed,Manhattan,Upper West Side,40.77886,-73.98042,Entire home/apt,2022.0,$410,$82,-2.0,129.0,2.0,1.0,381.0,strict,True
525,verified,Brooklyn,Bedford-Stuyvesant,40.68967,-73.95445,Entire home/apt,2022.0,$413,$83,-3.0,42.0,5.0,1.0,292.0,moderate,False
42446,verified,Bronx,Hunts Point,40.81731,-73.89052,Private room,2003.0,"$1,200",$240,-1223.0,0.0,2.0,4.0,341.0,moderate,False
42500,unconfirmed,Manhattan,Hell's Kitchen,40.76694,-73.98773,Entire home/apt,2009.0,$711,$142,-365.0,13.0,4.0,4.0,0.0,flexible,True
42538,verified,Brooklyn,Bedford-Stuyvesant,40.68470,-73.94350,Entire home/apt,2022.0,$85,$17,-200.0,3.0,2.0,1.0,157.0,moderate,True
69749,verified,Brooklyn,Williamsburg,40.71534,-73.94906,Private room,2012.0,$328,$66,-125.0,146.0,1.0,1.0,46.0,moderate,False
91271,unconfirmed,Manhattan,Midtown,40.74433,-73.98318,Entire home/apt,2007.0,$772,$154,-10.0,0.0,3.0,1.0,0.0,moderate,False
91357,verified,Brooklyn,Gowanus,40.67070,-73.99118,Shared room,2014.0,"$1,177",$235,-10.0,9.0,2.0,1.0,0.0,moderate,True

### Cleaning

In [11]:
# missing value are less than 1% we can drop those missing value
for col in df.columns:
    df.dropna(subset = [col], inplace = True)

In [12]:
df.isnull().sum()

host_identity_verified            0
neighbourhood group               0
neighbourhood                     0
lat                               0
long                              0
room type                         0
Construction year                 0
price                             0
service fee                       0
minimum nights                    0
number of reviews                 0
review rate number                0
calculated host listings count    0
availability 365                  0
cancellation_policy               0
instant_bookable                  0
dtype: int64

In [15]:
# Created a new column apartment. 
df['is_apartment'] = df["room type"].apply(lambda x: True if x == "Entire home/apt" else False)

In [16]:
# remove 'apt' from room type
df["room type"] = df["room type"].apply(lambda x: 'Entire home' if x == "Entire home/apt" else x)

In [17]:
# remove '$', ',' then convert to float
df["price"] = df["price"].replace('[\$,]', '', regex=True).astype(float)
df["service fee"] = df["service fee"].replace('[\$,]', '', regex=True).astype(float)

In [18]:
# check
df.sample(5)

,host_identity_verified,neighbourhood group,neighbourhood,lat,long,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,cancellation_policy,instant_bookable,is_apartment
89023,unconfirmed,Manhattan,Civic Center,40.71625,-74.00401,Entire home,2004.0,630.0,126.0,2.0,0.0,5.0,1.0,0.0,moderate,True,True
62418,verified,Queens,Astoria,40.75773,-73.91114,Entire home,2019.0,320.0,64.0,45.0,1.0,4.0,2.0,0.0,flexible,False,True
20450,unconfirmed,Queens,Ditmars Steinway,40.77664,-73.90896,Private room,2013.0,1000.0,200.0,30.0,79.0,2.0,2.0,0.0,moderate,True,False
9297,unconfirmed,Manhattan,East Village,40.72474,-73.98273,Private room,2008.0,581.0,116.0,1.0,1.0,1.0,1.0,352.0,flexible,True,False
69024,unconfirmed,Manhattan,Upper West Side,40.79259,-73.97238,Private room,2005.0,874.0,175.0,5.0,19.0,5.0,1.0,29.0,strict,False,False

In [19]:
# remove negative sign from availability 365, minimum nights
df['availability 365'] = df['availability 365'].abs()
df['minimum nights'] = df['minimum nights'].abs()

In [20]:
# check
df[df['availability 365'] < 0]

Empty DataFrame
Columns: [host_identity_verified, neighbourhood group, neighbourhood, lat, long, room type, Construction year, price, service fee, minimum nights, number of reviews, review rate number, calculated host listings count, availability 365, cancellation_policy, instant_bookable, is_apartment]
Index: []

In [21]:
# check
df[df['minimum nights'] < 0]

Empty DataFrame
Columns: [host_identity_verified, neighbourhood group, neighbourhood, lat, long, room type, Construction year, price, service fee, minimum nights, number of reviews, review rate number, calculated host listings count, availability 365, cancellation_policy, instant_bookable, is_apartment]
Index: []

In [44]:
# Replaced above 365 to 365.
df['availability 365'] = df['availability 365'].apply(lambda x: 365 if x > 365 else x)

### Feature Engineering

In [29]:
# Total stay cost
df['total stay cost'] = (df['price'] + df['service fee']) * df['minimum nights']

In [45]:
# Availability category
def available_category(available):
    if available == 0:
        return 'Unavailable'
    elif 1 <= available <= 180:
        return 'Seasonal'
    elif 181 <= available <= 364:
        return 'Mostly available'
    elif available == 365:
        return 'Full time'

In [48]:
df['availability category'] = df['availability 365'].apply(available_category)

In [49]:
df

,host_identity_verified,neighbourhood group,neighbourhood,lat,long,room type,Construction year,price,service fee,minimum nights,number of reviews,review rate number,calculated host listings count,availability 365,cancellation_policy,instant_bookable,is_apartment,total stay cost,availability category
0,unconfirmed,Brooklyn,Kensington,40.64749,-73.97237,Private room,2020.0,966.0,193.0,10.0,9.0,4.0,6.0,286.0,strict,False,False,11590.0,Mostly available
1,verified,Manhattan,Midtown,40.75362,-73.98377,Entire home,2007.0,142.0,28.0,30.0,45.0,4.0,2.0,228.0,moderate,False,True,5100.0,Mostly available
3,unconfirmed,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home,2005.0,368.0,74.0,30.0,270.0,4.0,1.0,322.0,moderate,True,True,13260.0,Mostly available
4,verified,Manhattan,East Harlem,40.79851,-73.94399,Entire home,2009.0,204.0,41.0,10.0,9.0,3.0,1.0,289.0,moderate,False,True,2450.0,Mostly available
5,verified,Manhattan,Murray Hill,40.74767,-73.97500,Entire home,2013.0,577.0,115.0,3.0,74.0,3.0,1.0,365.0,flexible,True,True,2076.0,Full time
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,verified,Brooklyn,Williamsburg,40.70862,-73.94651,Private room,2003.0,844.0,169.0,1.0,0.0,3.0,1.0,227.0,flexible,False,False,1013.0,Mostly available
102595,unconfirmed,Manhattan,Morningside Heights,40.80460,-73.96545,Private room,2016.0,837.0,167.0,1.0,1.0,2.0,2.0,365.0,moderate,True,False,1004.0,Full time
102596,unconfirmed,Brooklyn,Park Slope,40.67505,-73.98045,Private room,2009.0,988.0,198.0,3.0,0.0,5.0,1.0,342.0,moderate,True,False,3558.0,Mostly available
102597,unconfirmed,Queens,Long Island City,40.74989,-73.93777,Entire home,2015.0,546.0,109.0,2.0,5.0,3.0,1.0,365.0,strict,True,True,1310.0,Full time
102598,unconfirmed,Manhattan,Upper West Side,40.76807,-73.98342,Entire home,2010.0,1032.0,206.0,1.0,0.0,3.0,1.0,69.0,flexible,False,True,1238.0,Seasonal

In [50]:
# export cleaned for manual assessment again
df.to_excel("cleaned-bnb.xlsx")